# Generated by Django 3.2.5 on 2021-09-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
                ('Demand', models.IntegerField()),
            ],
        ),
    ]
