# Generated by Django 3.2.5 on 2021-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_elexon', '0002_alter_demand_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='Demand',
            field=models.CharField(max_length=200),
        ),
    ]
