# Generated by Django 3.2.5 on 2021-09-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('Intensity', models.IntegerField()),
            ],
        ),
    ]
