# Generated by Django 3.2.5 on 2021-09-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('GasTurbine', models.CharField(max_length=200)),
                ('Coal', models.CharField(max_length=200)),
                ('Nuclear', models.CharField(max_length=200)),
                ('Hydro', models.CharField(max_length=200)),
                ('Other', models.CharField(max_length=200)),
            ],
        ),
    ]
