# Generated by Django 3.2.5 on 2021-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wind_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windtype', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('Period', models.CharField(max_length=200)),
                ('EnergyGenerated', models.CharField(max_length=200)),
            ],
        ),
    ]
