# Generated by Django 3.2.5 on 2021-09-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freq_elexon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freq',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='freq',
            old_name='Frequency',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='freq',
            old_name='Time',
            new_name='time',
        ),
    ]
